# Generated by Django 5.1.2 on 2024-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_skills_styles_delete_mydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
