# Generated by Django 5.1.2 on 2024-11-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Education',
        ),
    ]
