# Generated by Django 5.1.2 on 2024-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_rename_about_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='text_field',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
