# Generated by Django 5.1.2 on 2024-11-20 19:15

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_alter_skills_text_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='styles',
            name='profile_image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
