# Generated by Django 5.1.2 on 2024-11-28 11:27

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_styles_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='background_image',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
