# Generated by Django 5.1.2 on 2024-11-28 11:33

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_education_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', sorl.thumbnail.fields.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='background_image',
        ),
    ]
