# Generated by Django 5.1.2 on 2024-11-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_edustyles_remove_education_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edustyles',
            old_name='background_image',
            new_name='image',
        ),
    ]
