# Generated by Django 5.1.2 on 2024-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0012_rename_background_image_edustyles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edustyles',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
